CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name="change_password"),
]

accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # request에 login된 user의 data가 저장되어 있기 때문에, variable routing을 안 쓴다. ! 
    path('signup/', views.signup, name = 'signup'),
    path('delete/', views.delete, name = 'delete'),
    path('update/', views.update, name = 'update'), 
]

articles/urls.py
from django.urls import path, include
from . import views 

app_name = 'articles'

urlpatterns = [
    
    # 전체 게시글 조회 
    path('', views.index, name='index'), 
    
    # 단일 게시글 조회 (detail 페이지)
    # variable routing 을 
    # 1) 조회 목적으로 사용한다. -> views.py에서 pk 매개변수로 받는다.  
    # 2) url naming pattern 에 pk를 사용한다. 
    path('<int:pk>/', views.detail, name='detail'), 
    
    # 새로운 게시글 만들기. 왜 두 개를 만들어야 할까? 
    # new로 정보를 받을거고(render), create로 DB에 등록한다(redirect)
    path('new/', views.new, name='new'), # 페이지 렌더링 
    path('create/', views.create, name = 'create'), # 페이지 리다이렉트 

    # variable routing : 조회 후 삭제 
    path('<int:pk>/delete', views.delete, name='delete'), 
    
    # variable routing : 조회 후 수정 
    path('<int:pk>/edit', views.edit, name='edit'), # 페이지 렌더링 
    path('<int:pk>/update', views.update, name='update'), # 페이지 리다이렉트 


]

accounts/models.py
from django.db import models

# Create your models here.

# AbstractUser : 로그인, 권한 관리 등에 필요한 기본적인 필드 제공 ! -> 설계도 파일 보면 다양하게 있다. 
from django.contrib.auth.models import AbstractUser

class User(AbstractUser): 
    pass 

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model): 

  title = models.CharField(max_length=100)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True) 
  updated_at = models.DateTimeField(auto_now=True) 
  

accounts/forms.py
# django auth 폼에서 유저 생성 폼, 유저 변경 폼 가져오기 
from django.contrib.auth.forms import UserCreationForm , UserChangeForm 

'''
# 직접 참조 : 
from .models import User

class CustomUserCreationForm(UserCreationForm): 
    class Meta(UserCreationForm.Meta): 
        model = User 
'''

# 간접 참조 :  
from django.contrib.auth import get_user_model 

# 생성 
class CustomUserCreationForm(UserCreationForm): 
    class Meta(UserCreationForm.Meta): 
        model = get_user_model() 

# 변경 
class CustomUserChangeForm(UserChangeForm): 
    class Meta(UserChangeForm): 
        model = get_user_model() 
        fields = ('first_name', 'last_name', 'email', ) # 어떤 회원정보를 변경할건지 

accounts/views.py
from django.shortcuts import render, redirect 
# Create your views here.

# 
from django.contrib.auth.forms import (
  AuthenticationForm, 
  UserCreationForm, 
  PasswordChangeForm,  
)
# 
# from .models import User

# 로그인, 로그아웃 기능 사용 
from django.contrib.auth import login as auth_login, logout as auth_logout 
# 
from .models import User

# login decorator ->  로그인한 사용자만 쓸 수 있는 기능 정의 
from django.contrib.auth.decorators import login_required

# 
from .forms import CustomUserCreationForm, CustomUserChangeForm

#
from django.contrib.auth import update_session_auth_hash

def index(request): 
    persons = User.objects.all()
    context = {
        'persons' : persons
    }
    return render(request, 'accounts/index.html', context)

def login(request): 
    if request.method == 'POST': # 로그인 버튼 눌렀을 때 
        form = AuthenticationForm(request, request.POST) # AuthenticationForm 의 첫 번째 인자 : request 
        # request.POST : 사용자가 입력한 ID, Password 
        # request : HTTP 요청 전체 
        if form.is_valid(): 
            auth_login(request, form.get_user())
            return redirect('articles:index') # 로그인 완료하면 메인 페이지로 

    else: # 로그인 버튼 누르기 전 
        form = AuthenticationForm() # 빈 폼 
    context = { 
        'form' : form 
    }
    return render(request, 'accounts/login.html', context)

@login_required # 로그인한 사용자만 사용할 수 있게 하는 기능   
def logout(request): 
    auth_logout(request) 
    return redirect('articles:index')
 
def signup(request): 
    # is_authenticated : 이미 인증된 사용자라면 
    if request.user.is_authenticated: 
        return redirect('articles:index') 
    
    if request.method == 'POST': 
        form = CustomUserCreationForm(request.POST) 
        if form.is_valid(): 
            user = form.save()
            auth_login(request, user) 
            return redirect('articles:index')
    else: 
        form = CustomUserCreationForm()
    context = {
        'form' : form , 
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def delete(request): 
    request.user.delete()
    # request.user : request에 포함되어 있는 user 정보 (현재 로그인되어있는) 
    return render('articles:index')

@login_required
def update(request): 
    if request.method == 'POST': 
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid(): 
            form.save()
            return redirect('articles:index') 
    else: # 회원 정보 버튼 누르기 전 
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form, 
    }
    return render(request, 'accounts/update.html', context) 
    

@login_required
def change_password(request, user_pk): 
    if request.method == 'POST': 
        form = PasswordChangeForm(request.user, request.POST) # 첫 번째 인자는 user, 두 번째 인자는 데이터 
        if form.is_valid(): 
            form.save() 
            # 세션 무효화 방지 과정 (자동 로그아웃 방지)
            # hash 함수로 현재 사용자의 인증 세션 갱신 
            update_session_auth_hash(request, user) 
            return redirect('articles:index')
    else: 
        form = PasswordChangeForm(request.user) 
    context = {
        'form' : form, 
    }
    return render(request, 'accounts/change_password.html', context) 

articles/views.py
from django.shortcuts import render, redirect

# Create your views here.
# 현재 디렉토리의 models.py에서 Article 모델을 가져오겠다. 
from .models import Article

def index(request): 
  # QuerySet API : 전체 데이터 조회 
  articles = Article.objects.all() 

  context = { 
    'articles' : articles
  }

  return render(request, 'articles/index.html', context)

# 단일 게시글 페이지 렌더링(조회) 
def detail(request, pk): # 매개변수로 pk도 받는다. url에 variable routing을 사용했으니까 
  # QuerySet API 가 단일 데이터 조회에 사용된다. (all 말고, get)
  # 단일 게시글 조회라 s를 제외한 article 로 받겠다. 
  article = Article.objects.get(pk=pk) # 뒤의 pk는 매개변수로 받은 pk. 앞의 pk는 인자
  context = {
    'article' : article, 
  }
  return render(request, 'articles/detail.html', context)

# index()와 detail()은 모두 QuerySetAPI가 사용되었지만, 
# index는 전체 데이터 조회라 .all() 메서드가 사용되었고, 
# detail은 단일 데이터 조회라 .get() 메서드가 사용되었다. 

def new(request): 
  return render(request, 'articles/new.html') 


# 페이지 리다이렉트, 데이터를 받아서 DB에 저장하기 때문에 GET 아니고 POST 방식   
  # GET 방식은 데이터가 url에 노출 -> 데이터를 조회, 검색할 때 사용 
  # POST 방식은 보안성이 좋아 -> 데이터를 생성, 수정, 삭제할 때 사용 (CSRF 토큰 활용)
# render와 redirect의 차이 
  # render : 사용자에게 새로운 페이지를 보여줄 때 사용 
  # redirect : 데이터 처리 후 다른 페이지로 이동하려 할 때 사용 
  # 게시글을 생성했다 하고, 이 작업이 끝나면 어떤 페이지로 이동할건가? 생각하면 redirect, render 구분할 수 있다. 

def create(request): 
  title = request.POST.get('title')
  content = request.POST.get('content')

  # 2번 저장법 - 코드가 간결하면서 안정성도 있다(save를 나중에 하니까)
  article = Article(title = title, content = content)
  # save 하기 전, 유효성 검사를 하기 때문에 안정성 검사를 이 줄에서 한다. 
  article.save()

  # 데이터를 변경하고 나면 
  # 클라이언트가 GET 요청을 한 번 더 보내도록 한다 (redirect)
  # 데이터가 변경되었을 때 경로에 요청 
  return redirect('articles:detail', article.pk)   

def delete(request, pk): 
  article = Article.objects.get(pk=pk) 
  article.delete() 
  return redirect('articles:index')

# create와 차이 ? 
# 기존에 있던 게시글 조회하는지/조회하지 않는지 
def edit(request, pk): 
  article = Article.objects.get(pk=pk) 
  context = {
    'article' : article 
  }
  return render(request, 'articles/edit.html', context)

def update(request, pk): 
  article = Article.objects.get(pk=pk) 
  article.title = request.POST.get('title')
  article.content = request.POST.get('content')
  article.save()

  return redirect('articles:detail', article.pk)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>비밀번호 수정</h1>
<form action="{% url "change_password" user.pk %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="비밀번호 수정">

</form>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>로그인</h1>
<form action="{% url "accounts:login" %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="로그인">

</form>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원가입</h1>
<form action="{% url "accounts:signup" %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="회원가입">

</form>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
<h1>회원정보 수정</h1>
<form action="{% url "accounts:update" %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="회원정보 수정">

</form>

{% endblock content %}

articles/templates/articles/detail.html
{% extends "base.html" %} 
{% comment %} 템플릿 상속받기 {% endcomment %}

{% block content %}

<h2> Detail </h2>

{% comment %} article은 view의 key다. {% endcomment %}
<h3> {{article.pk}} 번째 게시글 </h3>

<hr>

<h3> title : <br> </h3> <p> {{article.title}}</p>
<h3> content : <br> </h3> <p> {{article.content}}</p>
<h3> created_at : <br> </h3>  <p>{{article.created_at}}</p>
<h3> updated_at : <br> </h3>  <p>{{article.updated_at}}</p>

<form action="{% url "articles:delete" article.pk %}" method= POST>
  {% csrf_token %}
  {% comment %} value는 초기값 초기 페이지에 뜨는 글을 delete로 하겠다. {% endcomment %}
  <input type="submit" value= "delete">
</form>

<hr>
{% comment %} update {% endcomment %}
<a href="{% url "articles:edit" article.pk %}">[EDIT]</a>
{% comment %} delete {% endcomment %}
{% comment %} <a href="{% url "articles:delete" article.pk %}">[DELETE]</a> {% endcomment %}
{% comment %} back {% endcomment %}
{% comment %} 왔다갔다 편하게 하려고 urls.py에서 앱 네임, 기능 네임을 붙인 것  {% endcomment %}
<a href="{% url "articles:index" %}">[BACK]</a>

{% endblock content %}

articles/templates/articles/edit.html
{% extends "base.html" %}

{% block content %}


<h2> Edit </h2>

{% comment %} article은 view의 key다. {% endcomment %}

<hr>

{% comment %} 
form 태그로 POST 방식을 사용해 url을 1 -> 2 로 보낸다 ? 
1. url의 create 로 보내야 하나 ? 
2. view.py create() 함수의 인자, request로 들어가야 하나 ? 
{% endcomment %}

<form action="{% url "articles:update" article.pk %}" method= "POST">
  {% csrf_token %}
  <div>
    <label for="title">Title: </label>
    {% comment %} 아래 name='title'은 views.py의 request.POST.get()의 인자, 'title'과 연관있다. {% endcomment %}
    {% comment %} 위 for='title'과 아래 id='title'은 관련있다. {% endcomment %}
    <input type="text" name='title' id='title' value='{{article.title}}'>

  </div>

  <div>
    <label for="content"> Content: </label>
    <textarea name="content" id="content" cols="30" rows="10">{{article.content}}</textarea>
  </div>

  <input type="submit" value="수정하기">

</form>
<a href="{% url "articles:index" %}">[HOME]</a>

<hr> 


{% endblock content %}

articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<h3>안녕하세요, {{user.username}}님. </h3>
<h1>게시판</h1>

{% if request.user.is_authenticated %}

  {% comment %} <a href="{% url "accounts:logout" %}" method='POST'>로그아웃</a> {% endcomment %}
  <form action="{% url "accounts:logout" %}"method='POST'>
    {% csrf_token %}
    <input type="submit" value="로그아웃">
  </form>
  {% comment %} <a href="{% url "articles:new" %}">New</a> {% endcomment %}
  <form action="{% url "articles:new" %}">
    <input type="submit" value="새 게시글 생성">
  </form>
  <form action="{% url "accounts:delete" %}">
    {% csrf_token %}
    <input type="submit" value="회원 탈퇴">
  </form>
  <form action="{% url "accounts:update" %}">
    <input type="submit" value="회원정보 수정">
  </form>

{% else %}

  <a href="{% url "accounts:login" %}">로그인</a>
  <a href="{% url "accounts:signup" %}">회원가입</a>

{% endif %}

<hr>


{% for article in articles %}
  {% comment %} DTL 변수 {% endcomment %}

  <p> 글 ID : {{article.pk}} {% comment %} 객체.속성 접근{% endcomment %} </p>

  <a href="{% url "articles:detail" article.pk %}">
    <p> 글 제목 : {{article.title}} </p>
  </a>
  
  <p> 글 내용 : {{article.content}} </p>
  <hr>
{% endfor %}

{% endblock content %}

articles/templates/articles/new.html
{% extends "base.html" %}

{% block content %}


<h2> New </h2>

{% comment %} article은 view의 key다. {% endcomment %}

<hr>

{% comment %} 
form 태그로 POST 방식을 사용해 url을 1 -> 2 로 보낸다 ? 
1. url의 create 로 보내야 하나 ? 
2. view.py create() 함수의 인자, request로 들어가야 하나 ? 
{% endcomment %}

<form action="{% url "articles:create" %}" method= "POST">
  {% csrf_token %}
  <div>
    <label for="title">Title: </label>
    {% comment %} 아래 name='title'은 views.py의 request.POST.get()의 인자, 'title'과 연관있다. {% endcomment %}
    {% comment %} 위 for='title'과 아래 id='title'은 관련있다. {% endcomment %}
    <input type="text" name='title' id='title'>

  </div>

  <div>
    <label for="content"> Content: </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
  </div>

  <input type="submit">

</form>

<hr> 


{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  
  
  {% endblock content %}


</body>
</html>